version: '3.9'

services:
  unbound:
    image: klutchell/unbound:latest
    volumes:
      - ./unbound:/etc/unbound/custom.conf.d
    networks:
      - host-network

networks:
  host-network:
    name: host
    external: true
